matthias@md-droplet-01:/actions-runner-doppelganger$ docker ps -a
CONTAINER ID   IMAGE                  COMMAND            CREATED          STATUS                      PORTS     NAMES
f767c7d84feb   weatherboy-dop-image   "python main.py"   5 minutes ago    Exited (1) 5 minutes ago              trusting_fermi
5007b3d2739b   weatherboy-dop-image   "python main.py"   6 minutes ago    Exited (1) 16 seconds ago             weatherboy-dop
e63de54e9d50   weatherboy-main        "python main.py"   15 minutes ago   Exited (1) 15 minutes ago             nostalgic_grothendieck
f58815053905   7b3b4c1dbbff           "python main.py"   2 hours ago      Exited (1) 2 hours ago                focused_cohen
matthias@md-droplet-01:/actions-runner-doppelganger$ docker run weatherboy-dop-image
Traceback (most recent call last):
  File "/app/main.py", line 172, in <module>
    with open("data/daily_channels.txt", "w") as daily_channels_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/daily_channels.txt'
matthias@md-droplet-01:/actions-runner-doppelganger$


fix this issue with building the doppelganger